import Head from 'next/head';
import { FormEvent, useRef } from 'react';

import classNames from 'classnames';
import { Inter } from 'next/font/google';

import { MethodE } from '@/types';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const emailInputRef = useRef<HTMLInputElement>(null);
  const feebackInputRef = useRef<HTMLTextAreaElement>(null);

  const sunbmitFormHandler = (event: FormEvent) => {
    event.preventDefault();
    const email = emailInputRef.current?.value;
    const text = feebackInputRef.current?.value;

    // eslint-disable-next-line no-console
    console.log({ email }, { text });

    fetch('/api/feedback', {
      method: MethodE.POST,
      body: JSON.stringify({
        email,
        text,
      }),
      headers: {
        'Content-Type': 'application/json',
      },
    })
      .then(response => response.json())
      // eslint-disable-next-line no-console
      .then(data => console.log({ data }));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classNames(inter.className)}>
        <form onSubmit={sunbmitFormHandler}>
          <div className="field">
            <label htmlFor="email">Your email:</label>
            <input ref={emailInputRef} id="email" name="email" type="email" />
          </div>
          <div className="field">
            <label htmlFor="feedback">Your feedback:</label>
            <textarea
              ref={feebackInputRef}
              rows={5}
              id="feedback"
              name="feedback"></textarea>
          </div>
          <button>Send Feedback</button>
        </form>
      </main>
    </>
  );
}
